name: Deploy to EC2

on:
  push:
    branches:
      - lab_4

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 instance
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }} 
        username: ${{ secrets.SSH_USER }} 
        key: ${{ secrets.SSH_PRIVATE_KEY }} 
        script: |
          bash ~/DataBase/deploy.sh
